### ISSUE TITLE
Sortuniq seems to have a different behaviour

### ISSUE THREAD

**Issue by tontonsb** [0ki/shellscripts#1]
I looked through the scripts and was also surprised that the `sortuniq` script could be faster.

While testing I came upon realization that it might even not work the same as the other sorts.

```
$ dd if=/dev/urandom of=sortable bs=1M count=100
100+0 records in
100+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.10448 s, 1.0 GB/s

$ wc -l sortable
409650 sortable

$ cat sortable | ./sortuniq | wc -l
406650

$ cat sortable | sort -u | wc -l
404983

$ cat sortable | sort | uniq | wc -l
404983
```

Seems like something is treated differently in PHP as it leaves more lines.

**Comment by tontonsb** [comment]
However, speed wise you are entirely correct. I expected that a contemporary version `sort -u` could be faster than PHP, but no. OK, maybe the awk could do exactly the same as PHP? It's slow tho.

Here are my results over 10 runs of each (going round robin in a mixed order so overheating or caching doesn't affect the results). The file is the same randomly populated one.

command | time | stdev
-|-|-
`cat sortable \| ./sortuniq >/dev/null` | 0.59s | 0.06s
`cat sortable \| sort \| uniq >/dev/null` | 2.63s | 0.16s
`cat sortable \| sort -u >/dev/null` | 2.72s | 0.15s
`cat sorttest.dat \| awk '!x[$0]++' >/dev/null` | 1.51s | 0.04s
`cat sort sortable \| uniq >/dev/null` | 1.60s | 0.15s
`cat sort -u sortable >/dev/null` | 1.50s | 0.16s
`awk '!x[$0]++' sorttest.dat >/dev/null` | 1.37s | 0.02s


Btw while the results are not statistically convincing, it seems that `| sort | uniq` is faster than `| sort -u` while `sort <file> | uniq` is slower than `sort -u <file>`. I got it the other way around only once for each of these two pairs.

**Comment by 0ki** [comment]
Thanks for taking a look.
Behaviour is consistent when dealing with actual text files which is what's the tool was written for.
```
$ cat sortable |wc -l
410280
$ cat sortable |sortuniq|wc -l
407339
$ cat sortable |sort|uniq|wc -l
405590
$ cat sortable |onlyascii |wc -l
410280
$ cat sortable |onlyascii |sortuniq |wc -l
401185
$ cat sortable |onlyascii |sort|uniq |wc -l
401185
```

I haven't looked at the source of `sort` but I'd say that's what's doing crazy stuff, since manpage clearly says you need a textfile for it to work.
```
$ ls -s sortable 
4 sortable
$ md5sum sortable 
36dfdbdf862cdb4a8cdbea26f295958e  sortable
$ cat sortable | wc -l 
5
$ cat sortable | sort | wc -l 
6
```

**Comment by tontonsb** [comment]
While sort says you need a textfile, it's actually `uniq` that causes the difference. And `uniq` does not require text files, actually it thoroughly [works around](https://github.com/coreutils/gnulib/blob/master/lib/memcoll.c#L39) `\0`.

I found the key, tbh it's stated in the `uniq` manpage, but I overlooked it until I found `strcoll` used in the source.

> Also, comparisons honor the rules specified by 'LC_COLLATE'.

I'd say the behaviour of your code is more useful for logs and similar files. `uniq` finds lines to be equal if their sort order is equal and for many locales there are a lot of characters (japanese, arabic, hebrew, ...) that sort equal because their sort order is undefined.

Here's an example of a text file where this can be observed:

```
$ echo 'あ' > utf8file
$ echo 'い' >> utf8file
$ file utf8file
utf8file: UTF-8 Unicode text

$ sort -u utf8file
あ

$ (LC_COLLATE=en_US.UTF-8 sort -u utf8file)
あ

$ (LC_COLLATE=C sort -u utf8file)
あ
い

$ (LC_COLLATE=POSIX sort -u utf8file)
あ
い

$ (LC_COLLATE=C.UTF-8 sort -u utf8file)
あ
い
```

IMO that's something to keep in mind but nothing to fix here...

**Comment by 0ki** [comment]
Did you also take a look at why ` | sort | wc -l` sometimes shows more lines than ` | wc -l` ?

**Comment by tontonsb** [comment]
Ah, yes, `sort` adds a newline to every line, so that's where the behaviour is different if the input is not properly terminated.

```
$ echo -n -e '\x61\x0a\x62' > tf
$ file tf
tf: ASCII text


$ wc -l tf
1 tf

$ sort tf | wc -l
2

$ awk '!x[$0]++;' tf | wc -l
2

$ xxd tf
00000000: 610a 62                                  a.b

$ sort tf | xxd
00000000: 610a 620a                                a.b.

$ awk '!x[$0]++;' tf | xxd
00000000: 610a 620a                                a.b.
```

Your script seems to be the only one that leaves the last line verbatim without `\n`.

**Comment by pbirkants** [comment]
> However, speed wise you are entirely correct. I expected that a contemporary version `sort -u` could be faster than PHP, but no. OK, maybe the awk could do exactly the same as PHP? It's slow tho.

This comparison is somewhat unfair due to the fact that `sort -u` actually **sorts** the output, rather than just eliminates duplicate lines while preserving input order like the PHP and AWK versions do.

However, I tried running some tests on different sizes of random data with the script you provided in your PR, and it looks like the speedy version you're looking for is actually `LANG=C sort -u` :)
