### ISSUE TITLE
label:question onlyascii ?

### ISSUE THREAD

**Issue by ychaouche** [0ki/shellscripts#4]
Hello, 
What is the difference between onlyascii and the strings command ?
From the strings man page 
` strings - print the strings of printable characters in files.`

It is part of binutils.

**Comment by 0ki** [comment]
strings will look for string sequences and print them out each on their own line.
onlyascii will filter out nonprintable characters.

The main difference for my use-case being that strings will unfortunately inject newline characters in its output.
strings is not well suited to be passed as an *input* to a program expecting binary data.
